<?php
$dil = array(
"ziyaret"		=> "Siteyi Ziyaret Et",
"kacadet"		=> "Listede kaç adet gözüksün",
"ara"			=> "Ara",
"anasayfa"		=> "Anasayfa",
"pvplinkekle"	=> "Pvp Link Ekle",
"dilseciniz"	=> "Dil Seçiniz",
"trdil"			=> "Türkçe",
"ingdil"		=> "İngilizce",
"dedil"			=> "Almanca",
"rudil"			=> "Rusça",
"baslik"		=> "Başlık",
"durum"			=> "Durum",
"uridium"		=> "uridium",
"servertipi"	=> "Server Tipi",
"git"			=> "Git",
"yorumbirak"	=> "Bir Yorum Bırakın...",
"adsoyad"		=> "Adınız ve Soyadınız...",
"email"			=> "Eposta Adresiniz...",
"yorum"			=> "Yorumunuzu Yazın...",
"gonder"		=> "Gönder",
"onceki"		=> "Önceki",
"sonraki"		=> "Sonraki",
"acik"			=> "Açık",
"kapali"		=> "Kapalı",
"sitebasligi"	=> "Site Başlığını Yazın...",
"rakamsaldeger"	=> "Açıklama Girin...",
"kasilmalik"	=> "Kasılmalık",
"vslik"			=> "VSlik",
"bilinmiyor"	=> "Bilinmiyor",
"online"		=> "Online Ziyaretçi Sayısı",
);

?>
